export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';
export const ADD_PLANT = 'ADD_PLANT';
export const REMOVE_PLANT = 'REMOVE_PLANT';
export const RESET_PLANTS = 'RESET_PLANTS';
